[package]
name = "docker-campus"
version = "0.1.0"
authors = ["Tzu-ping Chung <uranusjr@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
directories = "2.0.2"
prettytable-rs = "0.10.0"
serde = { version = "1.0.101", features = ["derive"] }
toml = "0.5"
